### ISSUE TITLE
[SLACKBOT] Message slack when admin dashboard functions are executed

### ISSUE THREAD

**Issue by abigger87** [HackSC/odyssey#468]
We want visibility into who uses the admin dashboard and what functions they execute. The slackbot should post to a channel (e.g. eng-admin-visibility ) who executed the function, what function, when, ...

**Comment by abigger87** [comment]
- [x] Scan
  - Send slack message on scan
- [x] App Review
  - Sends slack message when user has completed their required # of reviews
- [x] Check In
  - Send slack message on check-in
- [x] Manage Roles
  - Send slack message on updated role
- [x] Manage Available Tasks
  - Send slack message on task create, update, and delete
- [x] Manage Houses
  - Send slack message on house create, update, and delete
- [x] Manage Event Schedule
  - Send slack message on event create and delete
- [x] Manage Hackers
  - Send slack message on CSV export
- [ ] Pass Judgement
- [x] Edit Battlepass
  - Send slack message on unlockable create, update, and delete
- [x] Mail Signups
  - Send slack message on CSV export
- [x] Manage API Directory
  - Send slack message on CSV export
- [x] Access Metabase
  - Send slack message on click
- [x] Experimental Console
  - Send slack message on executed query

**Comment by abigger87** [comment]
Need to fix judging process and add slack alerts

**Comment by MaxLeiter** [comment]
@abigger87 im not entirely sure we need slack messages for 'read only' events like CSV exports. Not worth removing any, but worth thinking about for the future (due to function limits)

**Comment by abigger87** [comment]
yup got it, i agree, for now i think its ok and ill leave it. over the next month or so we can test and if we hit the limit, I will pull them back.
